apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: $GRAFANA_INFLUX_ORG
      defaultBucket: $GRAFANA_INFLUX_BUCKET
      tlsSkipVerify: true
    secureJsonData:
      token: $GRAFANA_INFLUX_TOKEN
